name: video-search-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9.6
  - flask
  - mysql-connector-python
  - click # For creating beautiful command line interfaces
  - natsort
  - opencv
  - pandas
  - tqdm
  - scipy
  - tensorflow
  - pillow
  - python-dotenv
  